Reintroduce audit log
kyma-incubator/reconciler pull request #1017
Opened 2022-04-07 16:16 UTC by jakobmoellersap

2022-04-13 09:39 UTC, adityabhatia commented
/hold

2022-04-13 10:30 UTC, adityabhatia commented
/unhold

2022-04-13 15:37 UTC, tobiscr requested changes

2022-04-13 15:48 UTC, jakobmoellersap commented on cmd/mothership/mothership/start/http.go
> +	auditedPaths = []string{
Will include

2022-04-19 11:39 UTC, ruanxin submitted a review, later dismissed

2022-04-19 11:44 UTC, ruanxin commented on cmd/mothership/mothership/start/auditlog.go
> +	// Any Audit Log relevant entry will be a stateful change in POST/PUT/PATCH, GET can be ignored
```suggestion
	// Any Audit Log relevant entry will be a stateful change in POST/PUT/PATCH/DELETE, GET can be ignored
```

2022-04-19 15:56 UTC, jakobmoellersap commented
/test pre-main-reconciler-integration-k3d

2022-04-19 16:07 UTC, ruanxin approved these changes

2022-04-19 17:04 UTC, tobiscr approved these changes

2022-04-19 17:06 UTC, merged