Improve local scheduler
kyma-incubator/reconciler pull request #120
Opened 2021-08-30 09:59 UTC by skhalash

2021-08-31 06:30 UTC, lindnerby reviewed
Just an idea: Maybe since many operations on collections here, we introduce some functions for working with component collections?
https://gobyexample.com/collection-functions
Filter for example?

2021-08-31 06:30 UTC, lindnerby commented on pkg/scheduler/localscheduler.go
> +		if contains(ls.prerequisites, c.Component) {
Suggestion: Reduce nesting by continuing early:
```suggestion
		if !contains(ls.prerequisites, c.Component) {
		     continue
		}
```

2021-08-31 06:30 UTC, lindnerby commented on pkg/scheduler/localscheduler.go
> +		if contains(ls.componentsWithCRDs, c.Component) {
Same here, see above.

2021-08-31 06:30 UTC, lindnerby commented on pkg/scheduler/localscheduler.go
> +	}
Some empty lines after all if-statements of this function

2021-08-31 07:17 UTC, skhalash commented on pkg/scheduler/localscheduler.go
> +func WithComponentsWithCRDs(components []string) LocalSchedulerOption {
Agree, done

2021-08-31 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/reconciler?pullRequest=120) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/reconciler?pullRequest=120) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: skhalash<br/>:x: lindnerby<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/reconciler?pullRequest=120) it.</sub>

2021-09-01 08:18 UTC, skhalash commented on pkg/scheduler/localscheduler.go
> +		if contains(ls.prerequisites, c.Component) {
Done

2021-09-01 08:18 UTC, skhalash commented on pkg/scheduler/localscheduler.go
> +		if contains(ls.componentsWithCRDs, c.Component) {
Done

2021-09-01 09:00 UTC, tobiscr requested changes

2021-09-01 09:13 UTC, skhalash commented on cmd/local/cmd.go
> +	return ls.Run(context.Background(), keb.Cluster{
Done

2021-09-01 11:35 UTC, tobiscr approved these changes

2021-09-01 11:38 UTC, merged