Apply user configuration to Istio reconciler
kyma-incubator/reconciler pull request #1229
Opened 2022-11-04 16:56 UTC by cnvergence

2022-11-07 19:30 UTC, cnvergence commented
/retest

2022-11-08 10:32 UTC, cnvergence commented
/retest

2022-11-08 11:20 UTC, cnvergence commented
/retest

2022-11-08 13:33 UTC, cnvergence commented
/test pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d

2022-11-08 13:55 UTC, rakesh-garimella commented
/test pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d

2022-11-09 09:15 UTC, cnvergence commented
/retest

2022-11-09 12:27 UTC, tobiscr requested changes
@cnvergence : we have some collisions in the go.mod files.... otherwise, it looks good :)

2022-11-09 14:32 UTC, cnvergence commented on pkg/reconciler/instances/istio/merge/merge.go
> +	for _, cr := range istioCRList.Items {
Good question, I also thought about it, but I assumed that we would do some validation webhook for the IstioCR, to exclude the possibility of overwriting some of the configurations.
Other than that I don't see a problem with having more than one IstioCR.

2022-11-09 14:35 UTC, cnvergence commented on pkg/reconciler/instances/istio/clientset/provider.go
> +func restConfig(kubeconfigData string) (*rest.Config, error) {
In fact, we don't do it, the rename is a good suggestion

2022-11-09 15:04 UTC, cnvergence commented on pkg/reconciler/instances/istio/merge/merge.go
> +	err := json.Unmarshal([]byte(operatorManifest), &toBeInstalledIop)
As we have discussed, we will keep it here for now

2022-11-09 15:34 UTC, cnvergence commented
/retest

2022-11-10 08:23 UTC, triffer submitted a review, later dismissed

2022-11-10 10:08 UTC, barchw approved these changes

2022-11-10 10:35 UTC, cnvergence commented
@tobiscr go.mod applied, please take a look now :)

2022-11-10 13:22 UTC, tobiscr commented
/test pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d

2022-11-10 14:05 UTC, barchw commented
/hold

2022-11-10 14:06 UTC, barchw submitted a review, later dismissed
We need to configure default value for numTrustedProxies first

2022-11-14 09:34 UTC, cnvergence commented
/test pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d

2022-11-14 09:36 UTC, barchw approved these changes
/lgtm

2022-11-14 10:41 UTC, tobiscr approved these changes

2022-11-14 10:41 UTC, tobiscr commented
/test pre-main-reconciler-cli-kyma-prev-to-last-release-upgrade-k3d

2022-11-14 10:42 UTC, merged