Resolve node port conflict for internal docker registrey
kyma-incubator/reconciler pull request #1359
Opened 2023-06-14 14:07 UTC by dbadura

Changes:
- add action which solves the node port conflict.

2023-06-14 19:42 UTC, dbadura commented
/retest

2023-06-15 08:05 UTC, dbadura commented on pkg/reconciler/instances/serverless/nodeport.go
> +	svcs, err := k8sClient.CoreV1().Services(namespace).List(ctx, metav1.ListOptions{})
You should get all services from everynamespace

2023-06-15 08:07 UTC, kwiatekus requested changes

2023-06-15 08:07 UTC, kwiatekus commented on pkg/reconciler/instances/serverless/nodeport.go
> +	svcs, err := getAllNodePortServices(svcCtx.Context, k8sClient, svcCtx.Task.Namespace)
This should look up node port svc from all namespaces.

2023-06-15 09:45 UTC, kwiatekus requested changes

2023-06-15 09:45 UTC, kwiatekus commented on pkg/reconciler/instances/serverless/nodeport.go
> +		setNodePortOverride(svcCtx.Task.Configuration, dockerRegistryNodePortPath, currentNodePort)
shouldn't the new nodeport value be drawn in this case? I tested the code and it keeps applying the same nodeport ```
kubeClient failed to update Service 'serverless-docker-registry' (namespace: kyma-system)  with strategy 'PATCH': cannot patch "serverless-docker-registry" with kind Service: Service "serverless-docker-registry" is invalid: spec.ports[0].nodePort: Invalid value: 32137: provided port is already allocated
```

2023-06-15 10:03 UTC, kwiatekus commented on pkg/reconciler/instances/serverless/nodeport.go
> +	if svc != nil {
```suggestion
	if svc != nil && isNodePortType(svc) {
```

2023-06-19 13:47 UTC, kwiatekus approved these changes

2023-06-19 14:05 UTC, merged