WIP: Cache Kubeconfigs
kyma-incubator/reconciler pull request #1433
Opened 2024-01-18 12:43 UTC by jeremyharisch

2024-01-18 13:20 UTC, Tomasz-Smelcerz-SAP commented on pkg/cache/kubeConfig.go
> +	kubeConfigCache.DeleteExpired()
Out of curiosity: Is it necessary? Doesn't the cache evict items automatically/internally?

2024-01-18 13:40 UTC, Tomasz-Smelcerz-SAP commented on pkg/cache/kubeConfig.go
> +		SetKubeConfigInCache(runtimeID, kubeConfig)
No error is returned here. The "error condition" is only indicated by the `kubeConfig` being empty string.
If so, I recommend to only put this value into the cache if the string is not empty.

2024-01-18 13:44 UTC, Tomasz-Smelcerz-SAP commented on pkg/cache/kubeConfig.go
> +	runtimeID, kubeConfigName string) (secret *corev1.Secret, err error) {
`kubeConfigName` should be renamed to `secretResourceName` or something like that.

2024-01-18 13:56 UTC, Tomasz-Smelcerz-SAP commented on pkg/reconciler/instances/rma/integration_action.go
> +	mrand.New(mrand.NewSource(int64(binary.LittleEndian.Uint64(csum[0:8]))))
Same problem with `math/rand` - the returned object is not used, it looks like this has no effect.

2024-01-18 14:16 UTC, tobiscr commented
JFYI-  I have also a proposal (probably overlooked - I mentioned it in your Slack channel :D ): 

https://github.com/kyma-incubator/reconciler/pull/1432

2024-01-18 15:05 UTC, Tomasz-Smelcerz-SAP commented on pkg/cache/kubeConfig.go
> +	kubeConfigCache.DeleteExpired()
:+1:

2024-01-19 08:13 UTC, Tomasz-Smelcerz-SAP submitted a review, later dismissed

2024-01-19 08:28 UTC, tobiscr requested changes

2024-01-19 08:28 UTC, tobiscr commented on pkg/cache/kubeConfig.go
> +	}
This is acutally a failure and the process should stop with an error.

The logic currently implies that the developer who is using this method has to know that invalid values can be returned.

Explicit error handling by throwing an error avoid this.

2024-01-19 08:28 UTC, tobiscr commented on pkg/cache/kubeConfig.go
> +		return ""
Throw the error please, empty kubeconfigs are not valid. If the empty value gets returned, the callers of this method have to deal again with this exceptional case by their own.

2024-01-19 08:28 UTC, tobiscr commented on pkg/cluster/inventory.go
> +		if kubeconfig == "" {
Better to use an error in the response for indicating wrong values.

2024-01-19 08:30 UTC, tobiscr commented on pkg/cache/kubeConfig.go
> +			SetKubeConfigInCache(runtimeID, kubeConfig)
Using an error is better to indicate a wrong kubeconfig-value

2024-01-19 08:31 UTC, tobiscr commented on pkg/cache/kubeConfig.go
> +	kubeConfigCache.Set(key, kubeconfig, 5*time.Minute)
The method includes just one line of code and this line is also quite self-explaining. Wrapping by another method is not needed actually.

2024-01-19 09:37 UTC, tobiscr approved these changes

2024-01-19 09:42 UTC, tobiscr commented on pkg/cache/kubeConfig.go
> +	ttlcache.WithTTL[string, string](5*time.Minute),
Are 5min not too short? We reconcile with 20min intervals.. in theory we could increase the value to something <20min

2024-01-19 09:53 UTC, merged