Kyma version as label and disclaimer-warning as annotation
kyma-incubator/reconciler pull request #181
Opened 2021-09-16 12:39 UTC by rJankowski93

https://github.com/kyma-incubator/reconciler/issues/170

2021-09-16 14:40 UTC, tobiscr requested changes

2021-09-16 14:40 UTC, tobiscr commented on pkg/reconciler/service/annotationsinterceptor.go
> +	AnnotationReconcilerValue = "DO NOT EDIT - This resource is managed by Kyma.\nAny modifications are discarded and the resource is reverted to the original state."
```suggestion
	annotationReconcilerValue = "DO NOT EDIT - This resource is managed by Kyma.\nAny modifications are discarded and the resource is reverted to the original state."
```

2021-09-16 14:40 UTC, tobiscr commented on pkg/reconciler/service/annotationsinterceptor.go
> +	AnnotationReconcilerValue = "DO NOT EDIT - This resource is managed by Kyma.\nAny modifications are discarded and the resource is reverted to the original state."
The Key makes sense to have it public, but would make the value private.

2021-09-16 14:40 UTC, tobiscr commented on pkg/reconciler/service/annotationsinterceptor.go
> +	annotations[ManagedByAnnotation] = AnnotationReconcilerValue
```suggestion
	annotations[ManagedByAnnotation] = annotationReconcilerValue
```

2021-09-16 14:40 UTC, tobiscr commented on pkg/reconciler/service/annotationsinterceptor_test.go
> +				ManagedByAnnotation: AnnotationReconcilerValue,
```suggestion
				ManagedByAnnotation: annotationReconcilerValue,
```

2021-09-16 14:42 UTC, tobiscr commented on pkg/reconciler/service/annotationsinterceptor_test.go
> +				ManagedByAnnotation: AnnotationReconcilerValue,
```suggestion
				ManagedByAnnotation: annotationReconcilerValue,
```

2021-09-17 19:01 UTC, tobiscr approved these changes

2021-09-20 08:33 UTC, suleymanakbas91 approved these changes

2021-09-20 08:39 UTC, merged