Preserve existing pod-preset certs
kyma-incubator/reconciler pull request #354
Opened 2021-11-04 14:42 UTC by kwiatekus

**Related issue**
https://github.com/kyma-project/kyma/issues/12531
Requires kyma charts changes - https://github.com/kyma-project/kyma/pull/12540

2021-11-04 15:47 UTC, kwiatekus commented
Test it with:
```
./bin/mothership-darwin local --components cluster-essentials  --kubeconfig {path to your kubeconfig}  --version PR-12540
```

2021-11-08 10:28 UTC, tobiscr commented on .gitignore
> +pkup.sh
what is that? :D

2021-11-08 10:28 UTC, tobiscr requested changes

2021-11-08 10:28 UTC, tobiscr commented on .gitignore
> +pkup.sh
```suggestion
```

2021-11-08 10:58 UTC, kwiatekus commented on .gitignore
> +pkup.sh
removed

2021-11-08 12:22 UTC, moelsayed reviewed
Looks great, just a couple for minor comments.

2021-11-08 14:08 UTC, kwiatekus commented on pkg/reconciler/instances/clusteressentials/action.go
> +					context.Task.Configuration["pod-preset.caCert"] = string(w.ClientConfig.CABundle)
yup
https://github.com/kyma-incubator/reconciler/blob/c79cf22addc5bba86c16bd59c5366e7f76eb6cc0/cmd/reconciler/start/service/http.go#L68

2021-11-08 14:20 UTC, kwiatekus commented on pkg/reconciler/instances/clusteressentials/action.go
> +				if w.ClientConfig.CABundle != nil {
yes. thx. done

2021-11-08 14:20 UTC, kwiatekus commented on pkg/reconciler/instances/utils/utils.go
> +			configuration[overridePath], _ = strconv.ParseBool(secretValue)
done

2021-11-08 14:50 UTC, kwiatekus commented
/test pre-main-reconciler-protecode-guard

2021-11-08 22:07 UTC, tobiscr submitted a review, later dismissed

2021-11-09 03:28 UTC, moelsayed commented
/test pre-main-reconciler-protecode-guard

2021-11-09 07:38 UTC, rJankowski93 approved these changes

2021-11-09 07:39 UTC, merged