Add cluster status skipped
kyma-incubator/reconciler pull request #435
Opened 2021-11-18 11:12 UTC by rJankowski93

https://github.com/kyma-incubator/reconciler/issues/277

2021-12-13 13:33 UTC, tobiscr requested changes

2021-12-13 13:33 UTC, tobiscr commented on pkg/cluster/inventory.go
> +		notReconciledStatues, err := q.Select().
We should not always query the whole history.  Would propose following flow:

* Implement DB migration logic (will require #442 ) and migrate all ol pending-status which were not applied to `skipped`
* Check just the previous cluster-state status, and if this is `pending`, just change this one to `skipped`

2022-03-23 08:37 UTC, Ressetkk commented
/woof

2022-05-19 16:15 UTC, nachtmaar commented
@tobiscr Can we close this PR ?

2022-05-20 07:09 UTC, closed without merging

2022-05-20 07:09 UTC, tobiscr commented
Caused by strategy change to change the reconciler architecture to K8s native app, this feature isn't required anymore