Reconcile deletion error state
kyma-incubator/reconciler pull request #520
Opened 2021-12-02 10:00 UTC by jeremyharisch

2021-12-03 08:45 UTC, jeremyharisch commented
Please first merge #517 and then adapt this PR regarding this

2021-12-05 21:25 UTC, tobiscr requested changes

2021-12-05 21:25 UTC, tobiscr commented on pkg/model/clusterstatus.go
> +	ClusterStatusDeleteErrorRetryable    Status = "delete_error_retryable"
Please consider #528 - update of external API required before merging. We have to check with @piotrmiskiewicz how KEB is dealing with the new added statuses.

2021-12-08 11:34 UTC, tobiscr approved these changes

2021-12-08 11:53 UTC, merged