Added new cluster status to KEB contract
kyma-incubator/reconciler pull request #531
Opened 2021-12-06 09:31 UTC by jeremyharisch

2021-12-06 11:27 UTC, clebs commented on go.mod
> +	github.com/deepmap/oapi-codegen v1.8.2 // indirect
Seems strange that for such a small PR you get all these dependencies added 🤔 

Maybe check that you have the latest golang version and run go mod tidy.

2021-12-06 13:07 UTC, tobiscr requested changes
we have to migrate the cluster-table if we change the cluster-status from `error_retryable` to `reconcile_error_retryable`:

please update cluter-inventory table

2021-12-07 08:14 UTC, jeremyharisch commented
SQL migration was tested on local Backup of Dev environment - Works 👍🏻

2021-12-07 09:58 UTC, tobiscr approved these changes

2021-12-07 10:35 UTC, merged