Change workspace structure for downloaded components (#463)
kyma-incubator/reconciler pull request #580
Opened 2021-12-15 06:43 UTC by m00g3n

- Change workspace structure for downloaded components (#463)
- Fix external component workspace deletion (#450)

See also: 
- https://github.com/kyma-incubator/reconciler/issues/463
- https://github.com/kyma-incubator/reconciler/issues/527
- https://github.com/kyma-incubator/reconciler/issues/450

2021-12-22 11:38 UTC, tobiscr commented on pkg/reconciler/chart/component.go
> +func (c *Component) isRepository() bool {
Naming can be a bit confusing.. `component.isRepository()`  - maybe we could point out whether its an external component coming form a GIT repo, like `isExternalGitComponent` or something.

2021-12-22 11:40 UTC, tobiscr reviewed
Looks in general very good! Just one short comment

2021-12-22 11:42 UTC, tobiscr requested changes
Maybe we can use a bit more expressive name for `isRepository`.

2021-12-27 10:44 UTC, suleymanakbas91 approved these changes

2021-12-27 10:58 UTC, m00g3n commented
/test tide

2021-12-27 10:58 UTC, merged