Istio and istio-configuration components
kyma-incubator/reconciler pull request #704
Opened 2022-01-21 11:43 UTC by werdes72

See #698

2022-01-21 11:45 UTC, werdes72 commented
/test all

2022-01-25 06:39 UTC, werdes72 commented
/test all

2022-01-28 10:08 UTC, werdes72 commented
/retest

2022-01-30 18:57 UTC, tobiscr submitted a review, later dismissed

2022-02-01 06:56 UTC, mjakobczyk requested changes
Your solution does not work as expected. Please see my [comment](https://github.com/kyma-incubator/reconciler/issues/698#issuecomment-1026528213) for more details.

2022-02-01 09:19 UTC, mjakobczyk requested changes

2022-02-01 09:19 UTC, mjakobczyk commented on pkg/reconciler/instances/istio/action.go
> +	context.Logger.Debugf("Reconcile action of istio-configuration triggered")
Should it use formatted log when no formatting is used?

2022-02-01 09:19 UTC, mjakobczyk commented on pkg/reconciler/instances/istio/action.go
> +func NewReconcileIstioConfigurationAction(getIstioPerformer bootstrapIstioPerformer) *ReconcileAction {
Why do you return `ReconcileAction` which belongs to `istio` component?

2022-02-01 09:19 UTC, mjakobczyk commented on pkg/reconciler/instances/istio/action.go
> +	return (*ReconcileAction)(&ReconcileIstioConfigurationAction{getIstioPerformer})
As above.

2022-02-02 07:44 UTC, mjakobczyk approved these changes
Much better after changes, LGTM 👍

2022-02-02 10:08 UTC, merged