Add ensure-rafter-secret action
kyma-incubator/reconciler pull request #87
Opened 2021-08-11 07:07 UTC by moelsayed

Adds a new reconciler action to replace the `ensure-rafter-secret` helm hook in kyma 1.x:  #11794

2021-08-11 07:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/reconciler?pullRequest=87) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/reconciler?pullRequest=87) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/reconciler?pullRequest=87) it.</sub>

2021-08-12 07:43 UTC, moelsayed commented on go.mod
>  	gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
oops, auto import :/ I will fix it :+1:

2021-08-12 07:44 UTC, moelsayed commented on pkg/reconciler/instances/new-reconciler.sh
> +  sed -i "s/example/${compName}/g" "$file"
Yes. I use Linux. I thought it was a typo. I didn't think it's a compatibility issue! Thank you for including a Linux compatible fix, I will revert this one!

2021-08-12 07:48 UTC, moelsayed commented on pkg/reconciler/instances/rafter/rafter.go
> +			name: "ensure-rafter-secret",
Thank you! I am also using it for logging purpose :+1:

2021-08-12 11:19 UTC, dbadura requested changes
Good job, the action is ok.
Add unit test for this action.
I've done it this way:
https://github.com/kyma-incubator/reconciler/blob/a710c67212232a0c7b2541290ca519c467ad0a85/pkg/reconciler/instances/busolamigrator/action_test.go

2021-08-12 11:19 UTC, dbadura commented on pkg/reconciler/instances/rafter/action.go
> +		return fmt.Errorf("failed to get secret:%v", err)
I think that we can use `errors.Wrap(err)` here

2021-08-12 11:19 UTC, dbadura commented on pkg/reconciler/instances/rafter/action.go
> +		return errors.New("failed to create Rafter secert. AccessKey or SecretKey are empty")
Shouldn't we generate it if the values are empty?
https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/rafter/charts/controller-manager/charts/minio/templates/ensure-secret-job.yaml#L136

2021-08-12 13:39 UTC, tobiscr submitted a review, later dismissed

2021-08-12 13:39 UTC, tobiscr commented on pkg/reconciler/instances/rafter/rafter.go
> +			name: "ensure-rafter-secret",
👍

2021-08-18 09:34 UTC, moelsayed commented
/retest

2021-08-18 17:59 UTC, moelsayed commented
/retest

2021-08-19 06:20 UTC, dbadura commented on pkg/reconciler/instances/rafter/action_test.go
> +				assert.True(t, err != nil && kerrors.IsNotFound(err))
I would write it in this way:
```
require.NoError(t, err)
assert.True(t, kerrors.IsNotFound(err), "error is not not found error")
```
It tells a little more when assertion fails.

2021-08-19 06:20 UTC, dbadura commented on pkg/reconciler/instances/rafter/action_test.go
> +				assert.True(t, existingUID == secret.UID)
You can use `assert.Equal`. 
In case of failure it will write down what is not equal.

2021-08-19 06:20 UTC, dbadura commented on pkg/reconciler/instances/rafter/action_test.go
> +				assert.True(t, err != nil && kerrors.IsNotFound(err))
I would write it in this way:
```
require.NoError(t, err)
assert.True(t, kerrors.IsNotFound(err), "error is not not found error")
```
It tells a little more when assertion fails.

2021-08-19 06:20 UTC, dbadura commented on pkg/reconciler/instances/rafter/action_test.go
> +		{
We can add use test for `randAlphaNum` generating access key and key and check if size of string is ok.

2021-08-19 09:45 UTC, moelsayed commented
/retest

2021-08-19 11:24 UTC, dbadura approved these changes

2021-08-19 11:56 UTC, moelsayed commented
/retest

2021-08-19 12:13 UTC, moelsayed commented
/retest

2021-08-19 13:20 UTC, dbadura approved these changes

2021-08-20 06:34 UTC, tobiscr approved these changes

2021-08-20 06:35 UTC, merged