Always patch MutatingWebHook
kyma-incubator/reconciler pull request #971
Opened 2022-03-28 11:22 UTC by dariusztutaj

Added patching MutatingWebHook even in case of error during install/update istio

Related issues:
#967

2022-03-28 21:10 UTC, dariusztutaj commented
/retest

2022-03-29 08:58 UTC, mjakobczyk requested changes

2022-03-29 08:58 UTC, mjakobczyk commented on pkg/reconciler/instances/istio/action.go
> +			_ = performer.PatchMutatingWebhook(context.Context, context.KubeClient, context.Logger)
We should always catch an error

2022-03-29 08:58 UTC, mjakobczyk commented on pkg/reconciler/instances/istio/action.go
> +			errPatchMutatingWebhook := performer.PatchMutatingWebhook(context.Context, context.KubeClient, context.Logger)
We should just name error env as `err`

2022-03-29 08:58 UTC, mjakobczyk commented on pkg/reconciler/instances/istio/action.go
> +				context.Logger.Info("Could not patch MutatingWebhookConfiguration")
In case error appears we should propagate it to the upper layer. Even if we decided to log it then it should be `Error` instead of `Info`

2022-03-29 14:18 UTC, dariusztutaj commented
/retest

2022-04-06 05:52 UTC, dariusztutaj commented
Closing in case of too many changes have been made incorrectly, I lost. I'll create new clean PR

2022-04-06 05:52 UTC, closed without merging