Avoid logging client-go warnings in production
kyma-incubator/reconciler pull request #990
Opened 2022-04-01 11:29 UTC by moelsayed

Client-go can be a bit chatty with deprecation warnings to make sure users upgrade their resource versions. With the expected scale of the reconciler, this can generate an excessive amount of logs. 

This PR sets a `logr.Discard()` logger for client-go when verbose logging is disabled, effectively masking all warnings and logged errors coming from client-go. All errors are returned from client-go immediately, so this shouldn't mask any bugs. This is not an ideal solution but it's useful in this case considering the resources consumed by these logs.

This option applies to the local reconciler and individual component reconcilers.

2022-04-04 08:43 UTC, jakobmoellersap requested changes

2022-04-04 08:43 UTC, jakobmoellersap commented on cmd/mothership/mothership/start/scheduler.go
> +	runtimeBuilder := service.NewRuntimeBuilder(o.Registry.ReconciliationRepository(), logger.NewLogger(o.Verbose), o.Verbose)
I think here you are submitting the Verbose Flag twice. I suggest to omit this and instead use the Logger as intended and switch all log messages to debug unless they really need to be on info level. Then you won't have this issue anymore

2022-04-04 08:45 UTC, jakobmoellersap commented on cmd/mothership/mothership/start/scheduler.go
> +	runtimeBuilder := service.NewRuntimeBuilder(o.Registry.ReconciliationRepository(), logger.NewLogger(o.Verbose), o.Verbose)
Regarding the original issue of client-go, I suggest we mask the Log with our own, overwriting the Level in this case.

2022-04-05 07:00 UTC, moelsayed commented
We decided that these logs are too important to discard even on production. So, closing this for now.

2022-04-05 07:00 UTC, closed without merging